name: portfolio
description: "A Portfolio App"
publish_to: 'none'
version: 1.0.0
flutter_sdk_version: 3.27.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  provider: 6.1.2
  flutter_svg: 2.0.17
  url_launcher: 6.3.1
  flutter_sticky_header: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/social_share/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

